# Generated by Django 3.2.9 on 2021-11-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('second_name', models.CharField(max_length=250)),
                ('birth_day', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=11)),
            ],
        ),
    ]
