# Generated by Django 3.2.9 on 2021-12-01 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=11)),
                ('salary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salaries.salaryentry')),
            ],
        ),
    ]
